name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Change directory to react-fuchun
        run: cd react-fuchun

      - name: Install dependencies
        run: npm install
        working-directory: react-fuchun

      - name: Run tests
        run: npm run test
        working-directory: react-fuchun

      - name: Build project
        run: npm run build
        working-directory: react-fuchun